### ISSUE TITLE
Replace negation of instanceof without parenthesis with "not instanceof", too

### ISSUE THREAD

**Issue by jdreesen** [wbars/PHPFoldings#20]
Thanks for this great plugin! :)

In #7 you added support for replacing `!($foo instanceof Bar)` with `$foo not instanceof Bar`.

Because `instanceof` has higher operator precedence than `!` you can just write this without the parenthesis as `!$foo instanceof Bar` which currently does not get replaced. It would be nice if you could add support for this case, too.

**Comment by wbars** [comment]
Hi @jdreesen! Fix will be available in next plugin update.
